### ISSUE TITLE
Feedback Datadashboad

### ISSUE THREAD

**Issue by nerdale** [florenciasilva/cdmx-2018-06-bc-core-am-data-dashboard#16]
Queridas @florenciasilva y @Esthela1 
Estuve revisando el proyecto entregado y tengo algunos comentarios:

1. Les faltó completar el proyecto, lista algunos datos pero no todos e incluso de no todas las sedes, el de Santiago no lista nada por ejemplo.

2. Independiente del punto anterior, felicitaciones por todo el trabajo que hay detrás, se nota todo lo que pensaron e inclusa se ve una muy  buena separación entre lógica y manipulación del DOM. Felicitaciones por eso :clap: 

3. Se nota el estudio del usuario que hicieron, integraron las preguntas que hicieron y una muestra de las respeuestas que recibieron :heart: 

4. Ahora en cuanto a descriptivas que son con los nombres de funciones o variables, recuerden ser siempre muy explicitas incluso si eso significa un nombre larguísimo, pero es mucho más entendible que solo nombrar **lima** o **mexico** son contenedores? botones? inputs? recuerden que utilizamos una plataforma abierta como github donde podemos recibir codereview de cualquier desarrrollador del mundo.

5. No se ve orientación a test, ni siquiera en estructura como lo pedían los primeros test.

6. Ojo en el **index.html** tienen el mismo error en las líneas 41, 49, 64 y 70, tienen etiquetas con id pero el nombre del id sin comillas, eso es un error preocupante porque es algo básico que deberían manejar, lo tienen de esa manera --> `<article id=limaFifthInfo>`

7. Felicitaciones por seguir la línea gráfica de Laboratoria, la idea era que el producto no perdiera la esencia visual de sus usuarias que son partes de Laboratoria, así que felicitaciones por eso :clap: eso si deben manejar mejor la jerarquía y peso visual, hay elementos demasiado grandes para la plataforma y se escapa un poco de lo mostrado en los prototipos.

8. Faltó hacerlo responsive era uno de los requisitos del cliente, independiente de si el usuario lo prefería o no.

9. Ojo con los issues, no sirve de nada declararlos si no hay interacción alguna, no es crearlos por cumplir sino que deben utilizarlo como una herramienta más de gestión en su desarrollo. Todo esto lo digo especialmente por @Esthela1 que no interactuó, salvo en uno solo y con una pequeña frase. Se agradece el esfuerzo de @florenciasilva por crearlo pero eso no sirve de mucho si no hay participación de ambas. Deben trabajar este tema.

Las aliento a que mejoren/terminen el proyecto y que luego intenten hacer el código más eficiente, les será muy útil al momento de crear su portafolio

Vamos con todo en lo que se viene :metal: ustedes pueden!

**Comment by florenciasilva** [comment]
¡Muchas gracias por el feedback, Ale! ❤️

**Comment by Esthela1** [comment]
Gracias por el feedback, los tomaremos en cuenta para terminarlo 👍

**Comment by nerdale** [comment]
Vamos con todo chicas! todo el power :muscle:
