### ISSUE TITLE
Feedback Sprint 1 Datadashboard

### ISSUE THREAD

**Issue by nerdale** [florenciasilva/cdmx-2018-06-bc-core-am-data-dashboard#2]
Hola @Hensgrej y compañera

He estado revisando el proyecto y tengo algunos comentarios:

1. @Hensgrej debes agregar como colaboradora a **Esthela1**, es extremadamente necesario pues los issues van guiados hacia ambas.

2. De la mano del punto anterior veo que no realizaron los issues y milestones correspondientes al sprint 2 del proyecto, que pasó con eso?

3. Felicitaciones por realizar un pseudocódigo, sirve mucho para aclarar tanto la estructura de la data, como saber los datos que debo pedir y como acceder a ellos :clap: 

4. Felicitaciones también por la investigación de usuario que hicieron :clap: 

5. Recuerden utilizar HTML semántico `<header></header> <section></section> <aside></aside> <footer></footer> <article></article>`

6. Si bien ya acceden al objeto, les recomiendo comenzar a trabajar con la data a profundidad lo antes posible (se encontrarán con toda la lógica para jalar la información y hacer los cálculos) y plasmar tanto visual como funcionalmente lo que tienen pensado para el proyecto.

7. No olviden desarrollar desde los tests, tomense el tiempo de analizar que pide el test y desde ahí será mucho más sencillo la estructura a desarrollar

8. Ojo con el trabajo colaborativo en github, solo hay commits de @Hensgrej 

Vamos con todo el powerrrrr! :muscle: se que pueden, vamos vamos go go go !! :rocket:

**Comment by florenciasilva** [comment]
¡Muchas gracias por el feedback!

**Comment by Esthela1** [comment]
Gracias 👍
